// Code generated by swaggo/swag. DO NOT EDIT
package doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/contract-service": {
            "get": {
                "description": "This endpoint allows you to list all services in the contract",
                "tags": [
                    "service"
                ],
                "operationId": "listServiceInContract",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ServiceList"
                        }
                    }
                }
            }
        },
        "/request": {
            "get": {
                "description": "This endpoint allows you to list requests",
                "tags": [
                    "request"
                ],
                "operationId": "listRequest",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Processed",
                        "name": "processed",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.RequestList"
                        }
                    }
                }
            }
        },
        "/service": {
            "get": {
                "description": "This endpoint allows you to list all services in the database. Compared to the output from listServiceInContract, the service.url from this endpoint is the original URL of the service, which is not public.",
                "tags": [
                    "service"
                ],
                "operationId": "listService",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ServiceList"
                        }
                    }
                }
            },
            "post": {
                "description": "This endpoint allows you to register service in the contract",
                "tags": [
                    "service"
                ],
                "operationId": "registerService",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Service"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - success without response body"
                    }
                }
            }
        },
        "/service/{service}": {
            "get": {
                "description": "This endpoint allows you to get service by name",
                "tags": [
                    "service"
                ],
                "operationId": "getService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Service"
                        }
                    }
                }
            },
            "put": {
                "description": "This endpoint allows you to update service in the contract. The name attribute cannot be updated",
                "tags": [
                    "service"
                ],
                "operationId": "updateService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Service"
                        }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            },
            "delete": {
                "description": "This endpoint allows you to delete service in the contract",
                "tags": [
                    "service"
                ],
                "operationId": "deleteService",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Service name",
                        "name": "service",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/settle": {
            "post": {
                "description": "This endpoint allows you to settle fees for requests from users",
                "tags": [
                    "settle"
                ],
                "operationId": "settleFees",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/sync-account": {
            "post": {
                "description": "This endpoint allows you to synchronize information of all accounts from the contract",
                "tags": [
                    "user"
                ],
                "operationId": "syncUserAccounts",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/sync-service": {
            "post": {
                "description": "This endpoint allows you to synchronize all services from local database to the contract",
                "tags": [
                    "service"
                ],
                "operationId": "syncServices",
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        },
        "/user": {
            "get": {
                "description": "This endpoint allows you to list all users who have created accounts for your service",
                "tags": [
                    "user"
                ],
                "operationId": "listUserAccount",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.UserList"
                        }
                    }
                }
            }
        },
        "/user/{user}": {
            "get": {
                "description": "This endpoint allows you to get account by user address",
                "tags": [
                    "user"
                ],
                "operationId": "getUserAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User address",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.User"
                        }
                    }
                }
            }
        },
        "/user/{user}/sync": {
            "post": {
                "description": "This endpoint allows you to synchronize information of single account from the contract",
                "tags": [
                    "user"
                ],
                "operationId": "syncUserAccount",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User address",
                        "name": "user",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Accepted"
                    }
                }
            }
        }
    },
    "definitions": {
        "model.ListMeta": {
            "type": "object",
            "properties": {
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Request": {
            "type": "object",
            "required": [
                "fee",
                "inputFee",
                "nonce",
                "previousOutputFee",
                "serviceName",
                "signature",
                "userAddress"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "readOnly": true
                },
                "fee": {
                    "type": "string"
                },
                "inputFee": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "previousOutputFee": {
                    "type": "string"
                },
                "processed": {
                    "type": "boolean"
                },
                "serviceName": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "readOnly": true
                },
                "userAddress": {
                    "type": "string"
                }
            }
        },
        "model.RequestList": {
            "type": "object",
            "properties": {
                "fee": {
                    "type": "integer"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Request"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/model.ListMeta"
                }
            }
        },
        "model.Service": {
            "type": "object",
            "required": [
                "inputPrice",
                "model",
                "name",
                "outputPrice",
                "type",
                "url",
                "verifiability"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "readOnly": true
                },
                "inputPrice": {
                    "type": "string"
                },
                "model": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "outputPrice": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "readOnly": true
                },
                "url": {
                    "type": "string"
                },
                "verifiability": {
                    "type": "string"
                }
            }
        },
        "model.ServiceList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Service"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/model.ListMeta"
                }
            }
        },
        "model.User": {
            "type": "object",
            "required": [
                "user"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "readOnly": true
                },
                "lastBalanceCheckTime": {
                    "type": "string"
                },
                "lastRequestNonce": {
                    "type": "string"
                },
                "lastResponseFee": {
                    "type": "string"
                },
                "lockBalance": {
                    "type": "string"
                },
                "signer": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "unsettledFee": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "readOnly": true
                },
                "user": {
                    "type": "string"
                }
            }
        },
        "model.UserList": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.User"
                    }
                },
                "metadata": {
                    "$ref": "#/definitions/model.ListMeta"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "localhost:3080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "0G Serving Provider Broker API",
	Description:      "These APIs allow providers to manage services and user accounts. The host is localhost, and the port is configured in the provider's configuration file, defaulting to 3080.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
