/**
 * This is an autogenerated file. Do not edit this file manually.
 *
 * key_pair.ts gives private and public key for signing the requests 
 * in all test in the `Settle fees` section in serving.spec.ts.
 */

import { BigNumberish } from "ethers";

export const privateKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x407e45589dbea66f7a20d6660e59242d`),
    BigInt(`0xad2b4ecfdf9fe0fac014b27e36a0e34`),
];

export const publicKey: [BigNumberish, BigNumberish] = [
    BigInt(`0x6b27d649946764786034e62cac63809d`),
    BigInt(`0x876ab8e907a8ee0ce56f72e0aadb4207`),
];
