// Code generated by swaggo/swag. DO NOT EDIT
package doc

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/quote": {
            "get": {
                "description": "This endpoint allows you to get quote",
                "tags": [
                    "quote"
                ],
                "operationId": "getQuote",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/task": {
            "post": {
                "description": "This endpoint allows you to create fine tune task",
                "tags": [
                    "task"
                ],
                "operationId": "createTask",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Task"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content - success without response body"
                    }
                }
            }
        },
        "/task/{id}": {
            "get": {
                "description": "This endpoint allows you to get task by name",
                "tags": [
                    "task"
                ],
                "operationId": "getTask",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task ID",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/schema.Task"
                        }
                    }
                }
            }
        },
        "/tasks/{taskID}/progress": {
            "get": {
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "tasks"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Task ID",
                        "name": "taskID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "progress.log",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "schema.Task": {
            "type": "object",
            "required": [
                "customerAddress",
                "datasetkHash",
                "preTrainedModelHash",
                "trainingParams"
            ],
            "properties": {
                "createdAt": {
                    "type": "string",
                    "readOnly": true
                },
                "customerAddress": {
                    "type": "string"
                },
                "datasetkHash": {
                    "type": "string"
                },
                "deliverIndex": {
                    "type": "integer"
                },
                "encryptedSecret": {
                    "type": "string"
                },
                "fee": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "readOnly": true
                },
                "nonce": {
                    "type": "string"
                },
                "outputRootHash": {
                    "type": "string",
                    "readOnly": true
                },
                "preTrainedModelHash": {
                    "type": "string"
                },
                "serviceName": {
                    "type": "string"
                },
                "signature": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "teeSignature": {
                    "type": "string"
                },
                "trainingParams": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string",
                    "readOnly": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.2.0",
	Host:             "localhost:3080",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "0G Serving Provider Broker API",
	Description:      "These APIs allows customers to interact with the 0G Compute Fine Tune Service",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
