// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Request request
//
// swagger:model request
type Request struct {

	// created at
	CreatedAt string `json:"createdAt,omitempty"`

	// input count
	InputCount int64 `json:"inputCount,omitempty"`

	// nonce
	Nonce int64 `json:"nonce,omitempty"`

	// output count
	OutputCount int64 `json:"outputCount,omitempty"`

	// price
	Price string `json:"price,omitempty"`

	// provider address
	ProviderAddress string `json:"providerAddress,omitempty"`

	// service name
	ServiceName string `json:"serviceName,omitempty"`

	// updated at
	UpdatedAt string `json:"updatedAt,omitempty"`

	// user address
	UserAddress string `json:"userAddress,omitempty"`
}

// Validate validates this request
func (m *Request) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this request based on context it is used
func (m *Request) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Request) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Request) UnmarshalBinary(b []byte) error {
	var res Request
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
