/**
 * 0G Serving User Agent API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface ModelService { 
    inputPrice?: number;
    name?: string;
    outputPrice?: number;
    provider?: string;
    type?: string;
    updatedAt?: string;
    url?: string;
}
