/**
 * 0G Serving User Agent API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelListMeta } from './modelListMeta';
import { ModelRefund } from './modelRefund';


export interface ModelRefundList { 
    fee?: number;
    items?: Array<ModelRefund>;
    metadata?: ModelListMeta;
}
