/**
 * 0G Serving User Agent API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ModelRefund } from './modelRefund';


export interface ModelProvider { 
    balance?: number;
    lastResponseFee?: number;
    nonce?: number;
    pendingRefund?: number;
    provider?: string;
    refunds?: Array<ModelRefund>;
    signer?: Array<string>;
}
